import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import { Metadata } from 'next'
import { ThemeProvider } from '@/components/providers/ThemeProvider'
import { Outfit } from 'next/font/google';

const outfit = Outfit({
  weight: '300',
  subsets: ['latin'],
})


export const metadata: Metadata = {
  title: 'Discordia',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={outfit.className}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider >
  )
}
